### ISSUE TITLE
Remove dead/commented code and any unneeded library dependencies from requirements.txt

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/commons#41]
Among others, can the dependency for "prov" be removed?

**Comment by yuanzhou** [comment]
The `prov` dependency is only used by the deprecated `provenance.py` module. The handling of provenance moved to entity-api.

Another thing I thought about is we probably don't need the `requirements.txt` in commons because the commons is a package/library to be used by other services as dependency during installation. We already have the `setup.py` and the commons package can be installed with `pip install .` which would install the dependencies ( minimal versions, based on the version range if not pinned version) specified at  `install_requires` https://github.com/hubmapconsortium/commons/blob/test-release/setup.py#L18. 

Normally `requirements.txt` is often used to define the requirements for a complete Python environment, like our entity-api web service, thus all the dependencies in `requirementx.txt` should be exact versions for stable deployment. 

Currently the `install_requires` list is the same as `requirements.txt` without using pinned versions. We need to decide.
